version: "3.8"

services:
  emailing-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/emailing-service:main'
    hostname: emailing-service
    ports:
      - "8081:80"

  supply-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/supply-service:main'
    hostname: supply-service
    ports:
      - "8082:5432"

  employees-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/employees-service:main'
    hostname: employees-service
    ports:
      - "8083:80"
    depends_on:
      - emailing-service

  stock-api:
    image: 'ghcr.io/ozon-edu-csharp-2021/stock-api:main'
    hostname: stock-api
    ports:
      - "8084:80"
    depends_on:
      - supply-service

  merchandise-service:
    build: ../
    hostname: merchandise-service
    ports:
      - "8080:80"
    depends_on:
      - stock-api
      - emailing-service
      - employees-service
      - supply-service
    

    